name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - "release"

jobs:
  build:
    name: Bundle application
    runs-on: ubuntu-22.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Installing dependencies
        run: bun install --frozen-lockfile --production

      - name: Bundling package
        run: bun bundle
  publish:
    needs: [build]
    name: Publish to NPM Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Remove unnecessary files 
        run: rm -rf node_modules test tsconfig.json src docs bun.lockb

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}