name: Publish package

on:
  workflow_dispatch:
  push:
    tags:
      - "release"

jobs:
  build:
    name: Bundle application
    runs-on: ubuntu-22.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      
      - name: Installing dependencies
        run: bun install --frozen-lockfile --production

      - name: Bundling package
        run: bun bundle
  publish:
    needs: [build]
    name: Publish to NPM Registry
    runs-on: ubuntu-22.04
    steps:
      - name: Create release branch and bump version
        env:
          REF: ${{ github.ref }}
        run: |
          BRANCH=release/${REF:10}
          git config --local user.email "freitaseric@users.noreply.github.com"
          git config --local user.name "DDevs.js Publisher"
          git checkout -b $BRANCH
          git push -u origin $BRANCH
          sed -i "s/  '  "version": "Canary",/  "version": "${REF:11}",/' package.json
          git add package.json
          git commit -m "New DDevs.js release inbound!"
          git push

      - name: Remove unnecessary files 
        run: | 
          rm -rf node_modules test tsconfig.json src docs yarn.lock

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}